### ISSUE TITLE
我不会c++，请问可以发布一个release版本吗，exe或zip，谢谢

### ISSUE THREAD

**Issue by 1725636955** [SpriteOvO/AirPodsDesktop#1]

**Comment by SpriteOvO** [comment]
当然可以，我会在稍后发布一个 Pre-Release 版本。但由于该项目目前正在开发中，因此部分功能可能缺失不可用（比如 “Reduce loud sounds”）。

另外，该项目还未在公交、地铁等人多环境中进行过测试，因此在这些环境中可能会将他人的 AirPods 进行识别、显示电量等，一部分原因是苹果的隐私保护设计导致该问题无法根本性的修复，只能尽量避免。

期待您使用后的任何建设性的意见或问题反馈！

**Comment by 1725636955** [comment]
> 当然可以，我会在稍后发布一个 Pre-Release 版本。但由于该项目目前正在开发中，因此部分功能可能缺失不可用（比如 “Reduce loud sounds”）。
> 
> 另外，该项目还未在公交、地铁等人多环境中进行过测试，因此在这些环境中可能会将他人的 AirPods 进行识别、显示电量等，一部分原因是苹果的隐私保护设计导致该问题无法根本性的修复，只能尽量避免。
> 
> 期待您使用后的任何建设性的意见或问题反馈！

好的，谢谢，我会将我的使用情况及问题给您同步的，谢谢您的开源，麻烦您了

**Comment by SpriteOvO** [comment]
已发布 [v0.1.0 Beta](https://github.com/SpriteOvO/AirPodsDesktop/releases/tag/0.1.0) 版本。
