### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by Firnic** [SpriteOvO/AirPodsDesktop#10]
## :bug: **Describe the bug**
i saw a typo when i hover in the low right corner.

## :rocket: **Expected behavior**
i think you wanted to write charging

## :framed_picture: **Screenshots**
![typo](https://user-images.githubusercontent.com/45642630/129944731-0100ee54-b977-4c4b-9c61-d68da8d76476.PNG)

**Comment by SpriteOvO** [comment]
Thanks for reporting!
