### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by AlbyGNinja** [SpriteOvO/AirPodsDesktop#106]
Hello,
In the installation part I get this error:
```
CMake Error at C:/my/path/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:130 (find_package)


-- Configuring incomplete, errors occurred!
```
I've installed QT version 6.6.0 which includes `cmake.exe` into this path: `C:\Qt\Tools\CMake_64\bin`
Whatever I try using both `CMAKE_PREFIX_PATH` and `DCMAKE_PREFIX_PATH` pointing that folder I always get that error.
I tried to change the exe name into `qt5-config.cmake.exe` and using it for the `CMAKE_PREFIX_PATH` with no success.

The command I used on first attempt was the one I found in the README: `cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=C:\my\path\vcpkg\scripts\buildsystems\vcpkg.cmake ../`

Any tips please???

**Comment by SpriteOvO** [comment]
Qt6 is not compatible with Qt5, currently this project uses Qt5 as a dependency, so Qt6 path doesn't work.

Of course, it makes sense to upgrade and migrate to Qt6, I had a try about it, just got stuck with some compilation errors.

**Comment by SpriteOvO** [comment]
I will continue the work of upgrading to Qt6 in the future. For now, please use Qt5 to compile this project. Sorry for the inconvenience.
