### ISSUE TITLE
[not a Bug Report] help language

### ISSUE THREAD

**Issue by CatMow** [SpriteOvO/AirPodsDesktop#107]
## :bug: **Describe the bug**
no bug

i help english translate better

alright ill help to translate the english better, i can fluently speak chinese aswell

## :scroll: **To Reproduce**
Steps to reproduce the behavior
NO
## :rocket: **Expected behavior**
NO

## :framed_picture: **Screenshots**
NO

## :gear: **Environments:** 
 - OS: [e.g. Windows 10 20H2]
 - Version: [e.g. 0.1.0]
 ALL OF THEM

## :star2: **Additional context**
 just give me the .ts file...

<details><summary><b>AirPodsDesktop.log</b></summary>

```
Launch AirPodsDesktop with "--trace" parameter.
Then after the bug occurred, insert the contents of "AirPodsDesktop.log" here.
```
</details>

<details><summary><b>StackTrace.log</b></summary>

```
Insert the contents of "StackTrace.log" here, if any.
```
</details>

**Comment by CatMow** [comment]
@SpriteOvO 
yo
can .ts file pls
or do i just extract from my version of apd (latest)

**Comment by SpriteOvO** [comment]
Text for English in built-in, there is no `.ts` file for `en_US`. If you want to improve it, modify it directly from code.
