### ISSUE TITLE
[Feature Request] Add anti-aliasing to the corners of the pop-up window

### ISSUE THREAD

**Issue by UltimateTanA** [SpriteOvO/AirPodsDesktop#13]
I would like to suggest a very minor improvement that'd give some polish
if you notice the pop-up that comes up, it has corners that are kind of pixelated and not perfectly curved
it seems like i'm nitpicking but i think it's the thing that we all see every now and then and polishing it would make your tool much nicer to use
![image](https://user-images.githubusercontent.com/94423379/141889725-a05901cf-2d99-49af-8c20-d8bc58e5bb80.png)

**Comment by SpriteOvO** [comment]
Yes, it is worth improving. I have tried adding anti-aliasing to the edges before, but it doesn't seem to be as easy as I thought. Don't worry, I'll try again later.

**Comment by SpriteOvO** [comment]
Could you try this commit f456810890f8f45796c17be35d8094bae1299cd7? (You can download the installer of this commit from [GitHub CI](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1467802427))
It's still a bit pixelated, but for me it's a bit better than before.

The rounded corners implemented through the `WA_TranslucentBackground` flag would be perfect, but it doesn't work with `QVideoWidget` or `QMediaPlayer`, which causes the animation to not play. This is another fairly historical issue ([QTBUG-8119](https://bugreports.qt.io/browse/QTBUG-8119)) with Qt, and they don't seem to be planning to fix it :(

**Comment by UltimateTanA** [comment]
> Could you try this commit [f456810](https://github.com/SpriteOvO/AirPodsDesktop/commit/f456810890f8f45796c17be35d8094bae1299cd7)? (You can download the installer of this commit from [GitHub CI Artifacts](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1467802427)) It's still a bit pixelated, but for me it's a bit better than before.
> 
> The rounded corners implemented through the `WA_TranslucentBackground` flag would be perfect, but it doesn't work with `QVideoWidget` or `QMediaPlayer`, which causes the animation to not play. This is another fairly historical issue ([QTBUG-8119](https://bugreports.qt.io/browse/QTBUG-8119)) with Qt again, and they don't seem to be planning to fix it :(

Um I'm very new to Github and so I don't know how exactly to go about it
(fun fact, i created my account just to add this feature request)

**Comment by SpriteOvO** [comment]
Close since there may not be a better way to improve it further at present.
The implemented improvements will be available in the next release.
