### ISSUE TITLE
AirPods Pro Gen 2 not connecting

### ISSUE THREAD

**Issue by Nanolocity** [SpriteOvO/AirPodsDesktop#130]
## :bug: **Describe the bug**
AirPods Pro Gen 2 not connecting...? I'm connected via bluetooth but the app just says "Disconnected". I've tried to restart the app a handful of times and even using the previous version where supported was added for it in the first place.

## :scroll: **To Reproduce**
1. Enter the app
2. Success! Or rather, the lack of it...

## :rocket: **Expected behavior**
Connect my airpods

## :framed_picture: **Screenshots**
![image](https://github.com/user-attachments/assets/c9db4f4d-d084-4f37-9383-55a7488e6920)

## :gear: **Environments:** 
 - OS: Windows 11 Build 22631
 - Version: app version 0.4.1 & 0.4.0

## :star2: **Additional context**

<details><summary><b>[AirPodsDesktop.log](https://github.com/user-attachments/files/16339734/AirPodsDesktop.log)</b></summary>

```
Launch AirPodsDesktop with "--trace" parameter.
Then after the bug occurred, insert the contents of "AirPodsDesktop.log" here.
```
</details>

<details><summary><b>[AirPodsDesktop.log](https://github.com/user-attachments/files/16339764/AirPodsDesktop.log)</b></summary>

```
Insert the contents of "StackTrace.log" here, if any.
```
</details>

**Comment by Nanolocity** [comment]
And yes the "Cini Fülei" one is my AirPods if you couldn't tell but I assume you could figure it out from the "Find My" at the end

**Comment by Nanolocity** [comment]
Thanks, that solved it, but could you add some kind of counter to indicate the bluetooth threshold? Right now it's kind of hard to tell what it's set to but it works

**Comment by SpriteOvO** [comment]
The technical name of this value is [RSSI (Received signal strength indicator)](https://en.wikipedia.org/wiki/Received_signal_strength_indicator?useskin=vector). It doesn't have a standard unit, so it's not some kind of distance, and RSSI is negative, the closer it is to 0, the stronger the signal. For these reasons, I just placed a slider bar without showing its value.
