### ISSUE TITLE
[Feature Request] Close auto update dialog after manual update button clicked

### ISSUE THREAD

**Issue by AnnAngela** [SpriteOvO/AirPodsDesktop#19]
## :cloud_with_rain: **Is your feature request related to a problem? Please describe.**
When I clicked manual update button, the auto update dialog won't close automatically and the close button is disabled.

## :partly_sunny: **Describe the solution you'd like**
After manual update button clicked, the auto update dialog closes automatically.

## :cloud: **Describe alternatives you've considered**
It's another way that enabling the close button after clicking manual update button.

## :star2: **Additional context**
It's useful if the network condition is bad for downloading from github directly.

**Comment by SpriteOvO** [comment]
Thanks! It will be available in the next release.
