### ISSUE TITLE
Korean translation request

### ISSUE THREAD

**Issue by lu1z5ec** [SpriteOvO/AirPodsDesktop#22]
_Hello._
_Is it possible to provide Korean language support?_

**Comment by SpriteOvO** [comment]
@lu1z5ec Sure, if you are willing to translate it. I have created a new branch [l10n-ko_KR](https://github.com/SpriteOvO/AirPodsDesktop/tree/l10n-ko_KR) and added `ko_KR` locale and `.ts` file in commit 61621e930813b58f5c614ea97377422236c6bb08. You can fork this repo and checkout to that branch to start the translation, open a PR when you're done. Thanks!
