### ISSUE TITLE
Beats fit pro support

### ISSUE THREAD

**Issue by izikillz** [SpriteOvO/AirPodsDesktop#35]
## :partly_sunny: **Describe the solution you'd like**
its same chip as airpods pro so that should not be a problem

**Comment by SpriteOvO** [comment]
@izikillz Hi! Could you download [this version (artifact)](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/2087909377), then launch it with `--trace` parameter and post the log contents here? Thanks!

**Comment by izikillz** [comment]
[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/8458600/AirPodsDesktop.log).
i hope you mean this. here are the log file from other repo i could find too
[log2.txt](https://github.com/SpriteOvO/AirPodsDesktop/files/8458602/log2.txt)
[log1.txt](https://github.com/SpriteOvO/AirPodsDesktop/files/8458603/log1.txt)

**Comment by SpriteOvO** [comment]
@izikillz I have supported Beats Fit Pro in commit 130e09d4b12d584681e904d27ff323ebd3257161 and it should work now (except the animation, I will update it later). Could you help to test it? [CI artifact](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/2146254363)

**Comment by izikillz** [comment]
it worked thanks @SpriteOvO .

**Comment by izikillz** [comment]
has benn added as feature
