### ISSUE TITLE
Russian [ru_RU] translation request

### ISSUE THREAD

**Issue by osk115** [SpriteOvO/AirPodsDesktop#36]
Hi, I have created a translation of the program for the Russian language.
Translation file: https://gist.github.com/osk115/18dccec3901529ebeebde1be34cedfc1

**Comment by SpriteOvO** [comment]
@osk115 Thanks! I noticed that there are two texts that are still untranslated, could you complete it?

| Untranslated |
| - |
| "Translation Contributors:" |
| "Third-Party Libraries:" |

**Comment by SpriteOvO** [comment]
As there is no response, I have committed the current translation file to the repository. Please feel free to open a PR if you want to improve it.
