### ISSUE TITLE
[Feature Request] support for beats earphones such as powerbeats pro

### ISSUE THREAD

**Issue by AboodeDaBOSS** [SpriteOvO/AirPodsDesktop#40]

**Comment by SpriteOvO** [comment]
@AboodeDaBOSS Thanks for the report!

Could you launch this program with `--trace` parameter and post the log contents here? Powerbeats Pro is currently unsupported, as I don't have a device to test. If you could provide enough information, I would be happy to attempt to support it.

**Comment by AboodeDaBOSS** [comment]
I really don't understand what you mean by --trace if you could please guide me on how to do it I'd be happy to help you

**Comment by SpriteOvO** [comment]
> I really don't understand what you mean by --trace if you could please guide me on how to do it I'd be happy to help you

Open CMD or Powershell, execute `cd path\to\AirPodsDesktop` then `.\AirPodsDesktop.exe --trace` and wait for program to be opened.

Then, connect your AirPods in Windowss Bluetooth settings. Right-click the tray icon of this program, click on "Settings", click on "Open logs directory", upload the `*.log` files here.

**Comment by AboodeDaBOSS** [comment]
![image](https://user-images.githubusercontent.com/68856095/182726223-5694eaee-a863-421f-88e3-32c6b5427a9d.png)
[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/9255480/AirPodsDesktop.log)

**Comment by SpriteOvO** [comment]
@AboodeDaBOSS The log you provided indicates that AirPodsDesktop is not working properly with your Bluetooth device. This is similar to issue #38 and I have no idea about this problem at the moment. I will try to investigate it later. Thank you for your information!

If anyone who has PowerBeats can provide a log containing advertisements (this is the data broadcast by Bluetooth devices, you will see repeated items in the log, if there are advertisements received), please feel free to reply and I will check and try to support it.

**Comment by WoodsyLawyer** [comment]
> If anyone who has PowerBeats can provide a log containing advertisements (this is the data broadcast by Bluetooth devices, you will see repeated items in the log, if there are advertisements received), please feel free to reply and I will check and try to support it.

I have beats fit pro and this is the log I received following the same steps.  I got repeated "AirPods advertisement received, but device disconnected"



[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/10219193/AirPodsDesktop.log)

**Comment by SpriteOvO** [comment]
@WoodsyLawyer Thanks for your help! Please download and install the nightly version ([link](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/3583178195)) and update the logs here.

**Comment by WoodsyLawyer** [comment]
@SpriteOvO Here's the updated logs with the nightly version

[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/10224423/AirPodsDesktop.log)

**Comment by SpriteOvO** [comment]
Support for Beats Fit Pro has been released in [v0.4.0](https://github.com/SpriteOvO/AirPodsDesktop/releases/tag/0.4.0). For other products, please open a new issue with logs.
