### ISSUE TITLE
steps to download the application  [Bug Report] 

### ISSUE THREAD

**Issue by AboodeDaBOSS** [SpriteOvO/AirPodsDesktop#42]
## :gear: **Environments:** 
 - OS: [e.g. Windows 10 20H2]
 - Version: [e.g. 0.1.0]

## :star2: **Additional context**

<details><summary><b>AirPodsDesktop.log</b></summary>

```
Launch AirPodsDesktop with "--trace" parameter.
Then after the bug occurred, insert the contents of "AirPodsDesktop.log" here.
```
</details>

<details><summary><b>StackTrace.log</b></summary>

```
Insert the contents of "StackTrace.log" here, if any.
```
</details>

**Comment by SpriteOvO** [comment]
See [releases page](https://github.com/SpriteOvO/AirPodsDesktop/releases).

**Comment by AboodeDaBOSS** [comment]
sir how can i download it i cant find any executable file or any text to use in cmd or powershell?
