### ISSUE TITLE
need Linux Release

### ISSUE THREAD

**Issue by betteryjs** [SpriteOvO/AirPodsDesktop#43]
I try to use cmake to build the project on ubuntu 20.04 The branch taken is Linux, the QT version is the same, can You add the release of Linux?

**Comment by SpriteOvO** [comment]
Like I said before in https://github.com/SpriteOvO/AirPodsDesktop/issues/28#issuecomment-1217885292. It currently just passes compilation, but the platform specific code is still not implemented, it's functions are not working completely.

It doesn't make sense to me and other users to release a version at such a stage.
