### ISSUE TITLE
[Feature Request] Auto Pop-up

### ISSUE THREAD

**Issue by RonaldIp** [SpriteOvO/AirPodsDesktop#49]
## :cloud_with_rain: **Is your feature request related to a problem? Please describe.**
Maybe include an auto pop-up where you could see the animations automatically appear in the center of the screen when the AirPods are within range, like iOS and iPadOS.
## :partly_sunny: **Describe the solution you'd like**
Just the AirPods animations pop up when in range, maybe another setting to change how close you have to hold them until they appear.
## :cloud: **Describe alternatives you've considered**
Nothing else.

**Comment by SpriteOvO** [comment]
I believe this is a feature that has already been implemented, for now the main window of AirPodsDesktop will automatically pop up in the bottom right corner of the screen when the lid of the paired AirPods is opened and connected to the computer, and then the window will automatically disappear when you take any of the earphones out of the case.
