### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by aetrnm** [SpriteOvO/AirPodsDesktop#55]
I can help translate the program in French. Want to request a `.ts` translation file.

**Comment by SpriteOvO** [comment]
@aetrnm Hi! I have created a new branch [l10n-fr_FR](https://github.com/SpriteOvO/AirPodsDesktop/tree/l10n-fr_FR) and added `fr_FR` locale and `.ts` file in commit https://github.com/SpriteOvO/AirPodsDesktop/commit/0532655d353d2a6bea8f5799fef5977d770df5c3. You can fork this repo and checkout to that branch to start the translation work, then open a PR when you're done. Fell free to ask me if you have any questions, thanks in advance!

**Comment by SpriteOvO** [comment]
Close as completed in PR #56, thanks!
