### ISSUE TITLE
i cant bind my airpods

### ISSUE THREAD

**Issue by zMuh** [SpriteOvO/AirPodsDesktop#57]
when i try to open the program it dosent detect my air pods i tried to unpair it and i still have the same problem 

i have air pods pro gen 2

![image](https://user-images.githubusercontent.com/85467517/210163665-5fe684f4-61ac-473c-a4b1-adf817a5ec1b.png)

[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/10328464/AirPodsDesktop.log)

**Comment by mikhailfluffy** [comment]
I think It's not supported. Last update was 4 Feb 2022

**Comment by miguelreb** [comment]
Same problem here.

**Comment by dener120** [comment]
Similar problem

**Comment by CaptainMudkip1** [comment]
Same problem.

**Comment by Jadtrugaming** [comment]
@SpriteOvO When do you think this will be fixed?

**Comment by jbird2409** [comment]
i have orginal airpods gen 2 and same here

**Comment by DanielOberlechner** [comment]
I've got this issue with my Apple Airpods Max and I don't know how to fix it ...
If anyone has an idea just hit me up please :)

**Comment by shinjaxu** [comment]
Same problem

**Comment by SpriteOvO** [comment]
Duplicate of #46. Will be release in a few hours.
