### ISSUE TITLE
Unavailable message

### ISSUE THREAD

**Issue by boobthecat** [SpriteOvO/AirPodsDesktop#73]
## :bug: **Describe the bug**
App says it's unavailable

## :scroll: **To Reproduce**
1. Open program
2. Try to bind the airpods
3. See error

## :rocket: **Expected behavior**
Expected to show the message to bind

## :framed_picture: **Screenshots**
![image](https://github.com/SpriteOvO/AirPodsDesktop/assets/127695532/ce3b214f-80c5-4c84-b21a-6822a6a70487)

## :gear: **Environments:** 
 - OS: Win 10 22H2
 - Version: 0.4.0

## :star2: **Additional context**

 
[AirPodsDesktop.txt](https://github.com/SpriteOvO/AirPodsDesktop/files/12196863/AirPodsDesktop.txt)

**Comment by boobthecat** [comment]
It seems to have fixed itself after uninstalling 3 times... :P
![image](https://github.com/SpriteOvO/AirPodsDesktop/assets/127695532/932a7836-07ae-44c5-b0ae-d7255241d40a)

**Comment by GameEntity903** [comment]
I am experiencing the same issue. 
OS : 22H2
Ver 0.4.1
[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/13402448/AirPodsDesktop.log)
