### ISSUE TITLE
Low audio latency mode

### ISSUE THREAD

**Issue by 777AoD777** [SpriteOvO/AirPodsDesktop#74]
No issues just wanted to know how Low audio latency mode works. Also what is the difference in latency between having it on and off.

**Comment by SpriteOvO** [comment]
Normally, if there is no sound output from your system for a period of time, AirPods will go into an inactive mute mode. Then when your system makes sound, it takes a short time (about 1 second or so) between switching from inactive to active mode. This results in the possibility that AirPods may not produce any sound if your system plays a sound shorter than 1 second, or you may only hear the incomplete second half of the sound. low audio latency solves this problem by looping a silent MP3 to keep AirPods active.

**Comment by 777AoD777** [comment]
> Normally, if there is no sound output from your system for a period of time, AirPods will go into an inactive mute mode. Then when your system makes sound, it takes a short time (about 1 second or so) between switching from inactive to active mode. This results in the possibility that AirPods may not produce any sound if your system plays a sound shorter than 1 second, or you may only hear the incomplete second half of the sound. low audio latency solves this problem by looping a silent MP3 to keep AirPods active.

Ah ok, thank you

**Comment by SpriteOvO** [comment]
> Any chance of an android app in the future?

For Android, you can use [OpenPods](https://github.com/adolfintel/OpenPods).
