### ISSUE TITLE
[Bug Report] Strange behavior of "About" context menu item

### ISSUE THREAD

**Issue by Lingxi-Li** [SpriteOvO/AirPodsDesktop#78]
## :bug: **Describe the bug**
The "About" right-click context menu item takes me to following "hidden" tab.

![image](https://github.com/SpriteOvO/AirPodsDesktop/assets/11997203/967ebed8-7683-4af4-9609-105bafeaa2d2)

Two issues.

1. Thought it should take me to the "About" tab.
2. I don't see a way to access this "hidden" tab otherwise.

![image](https://github.com/SpriteOvO/AirPodsDesktop/assets/11997203/d430b892-4af0-4f1c-8747-1aca6f9c7ad2)

## :gear: **Environments:** 
 - OS: Windows 11 22H2
 - Version: 22621.2134

**Comment by SpriteOvO** [comment]
Fixed in #80, thanks!
