### ISSUE TITLE
[Bug Report] Program crashes when trying to open it for the first time

### ISSUE THREAD

**Issue by nightlyonie** [SpriteOvO/AirPodsDesktop#8]
## :bug: **Describe the bug**
I wanted to try out this program, but it always crashes while it displays the "Hello, welcome to AirPodsDesktop!" message for about a second.

## :scroll: **To Reproduce**
1. Install the program on a copy of Windows where this program was never installed on
2. Try to open the program for the first time

## :rocket: **Expected behavior**
The program crashes after a second or two, without an error message.

*edit: I forgot a word between "crashes" and "a second or two"*

## :framed_picture: **Screenshots**
Not a screenshot, but a screen recording of the crash: 
https://user-images.githubusercontent.com/45924578/129070327-f94594f7-c86a-4fea-b938-35ddda674019.mp4

## :gear: **Environments:** 
 - OS: Windows 10 21H1 (Build 19043.1151)
 - Version: 0.2.0

## :star2: **Additional context**
I don't think this needs any additional context. If so, please reply with the things that would be important as well to fix this issue.

**Comment by SpriteOvO** [comment]
@nightlyonie Hi, thanks for reporting!
Could you launch the program with the "--trace" argument and send its log file here?
The log file should be in this location: `C:\Users\<UserName>\AppData\Local\AirPodsDesktop`

**Comment by nightlyonie** [comment]
I did it, and here's the log file: [AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/6970156/AirPodsDesktop.log)

**Comment by SpriteOvO** [comment]
@nightlyonie Thanks, I just pushed a fix, can you try it working properly? You can download it from the [CI artifact](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1121021969) later.

**Comment by nightlyonie** [comment]
It works properly now, but there's another issue I'm noticing when the small window pops up. (there are no icons for the AirPods themselves or their case, like in the preview)
![image](https://user-images.githubusercontent.com/45924578/129076998-f9e367fe-f60e-4a91-a638-ad1134ab09d9.png)

**Comment by SpriteOvO** [comment]
Supplement: Maybe you'll see a "Bind to AirPods" button every time you launch AirPodsDesktop, this is not expected, click it to make it disappear, it will be fixed in the next release, as the earlier code lacked proper design and they needed time to be refactored.
