### ISSUE TITLE
[Feature Request] Want to help add Traditional Chinese into your language pack

### ISSUE THREAD

**Issue by chucheliu** [SpriteOvO/AirPodsDesktop#85]
## :cloud_with_rain: **Is your feature request related to a problem? Please describe.**
No, this request is not related to any problem.

## :partly_sunny: **Describe the solution you'd like**
Translate English to Traditional Chinese

## :cloud: **Describe alternatives you've considered**
None.

## :star2: **Additional context**
None.

**Comment by SpriteOvO** [comment]
@chucheliu Hi! I have created a new branch [l10n-zh_TW](https://github.com/SpriteOvO/AirPodsDesktop/tree/l10n-zh_TW) and added `zh_TW` locale and `.ts` file in commit 7a6553df90ef639097217f748c37a83fe723597c. The next step, you should fork this repo and checkout to that branch to start the translation work, then open a PR when you're done.

About how to process `.ts`, please read [Translation Guide](https://github.com/SpriteOvO/AirPodsDesktop/blob/main/CONTRIBUTING.md#-translation-guide), start at step 2.

Fell free to ask me if you have any questions, thanks in advance!

**Comment by SpriteOvO** [comment]
Someone else has already done this work in #89, thank you anyway.
