### ISSUE TITLE
[Feature Request] Low battery visual notification

### ISSUE THREAD

**Issue by luoluomeng** [SpriteOvO/AirPodsDesktop#9]
## :cloud_with_rain: **Is your feature request related to a problem? Please describe.**
Usually forgot to check the battery level.

## :partly_sunny: **Describe the solution you'd like**
Add a battery monitor mechanism that monitors the battery and notice the user with a visual method when the battery is low.

## :cloud: **Describe alternatives you've considered**
1. Able to configure the battery warning level (10% 20% 30%, etc)
2. Visualized notification(change the tray icon's color, popup a toast, etc.)

## :star2: **Additional context**
TBD

**Comment by SpriteOvO** [comment]
I considered your first suggestion. On the iPhone the battery warning value is < 20%, and currently in the program the AirPods' battery always changes in 10% steps, so <= 20% is probably the most appropriate. So configuring the battery warning value may not be very useful at the moment.

The second suggestion has been implemented in bccac68aee84823ccc938cb1d5a6c4ff6dd771e9.

**Comment by SpriteOvO** [comment]
Released [v0.3.0](https://github.com/SpriteOvO/AirPodsDesktop/releases/tag/0.3.0).
